#!/bin/bash
#
# Fail2ban Setup Script
# Installs and configures fail2ban on Ubuntu/Debian systems
#

set -e  # Exit on error

echo "========================================="
echo "  Fail2ban Setup Script"
echo "========================================="
echo ""

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root or with sudo" 
   exit 1
fi

# Detect log file path
if [ -f "/var/log/auth.log" ]; then
    LOG_PATH="/var/log/auth.log"
elif [ -f "/var/log/secure" ]; then
    LOG_PATH="/var/log/secure"
else
    LOG_PATH="/var/log/auth.log"
fi

# Get SSH port
SSH_PORT=$(grep "^Port" /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}')
if [ -z "$SSH_PORT" ]; then
    SSH_PORT="ssh"
fi

# Install fail2ban
echo "[1/4] Installing fail2ban..."
if command -v apt &> /dev/null; then
    apt update
    apt install fail2ban -y
elif command -v yum &> /dev/null; then
    yum install epel-release -y
    yum install fail2ban -y
else
    echo "Unsupported package manager"
    exit 1
fi

# Create local configuration
echo ""
echo "[2/4] Creating configuration..."

# Backup if exists
if [ -f "/etc/fail2ban/jail.local" ]; then
    BACKUP="/etc/fail2ban/jail.local.backup.$(date +%Y%m%d-%H%M%S)"
    cp /etc/fail2ban/jail.local "$BACKUP"
    echo "Existing config backed up to: $BACKUP"
fi

# Create jail.local with SSH protection
cat > /etc/fail2ban/jail.local <<EOF
# Fail2ban local configuration
# Generated by fail2ban setup script

[DEFAULT]
# Ban time: 1 hour (3600 seconds)
bantime = 3600

# Find time window: 10 minutes (600 seconds)
findtime = 600

# Number of failures before ban
maxretry = 3

# Ignore localhost and private IPs (add your IPs here!)
ignoreip = 127.0.0.1/8 ::1

# Email settings (configure if needed)
# destemail = admin@example.com
# sendername = Fail2Ban
# mta = sendmail
# action = %(action_mwl)s

# Default action (ban only, no email)
action = %(action_)s

# SSH jail
[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = $LOG_PATH
maxretry = 3
bantime = 3600
findtime = 600

# SSH aggressive (stricter)
[sshd-aggressive]
enabled = false
port = $SSH_PORT
filter = sshd
logpath = $LOG_PATH
maxretry = 1
bantime = 86400
findtime = 3600

# Recidive - ban repeat offenders for longer
[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
bantime = 604800
findtime = 86400
maxretry = 3
EOF

echo "✓ Configuration created at /etc/fail2ban/jail.local"

# Enable and start fail2ban
echo ""
echo "[3/4] Starting fail2ban..."
systemctl enable fail2ban
systemctl restart fail2ban
sleep 2

# Verify status
echo ""
echo "[4/4] Verifying installation..."
if systemctl is-active --quiet fail2ban; then
    echo "✓ Fail2ban is running"
else
    echo "✗ Fail2ban failed to start"
    journalctl -u fail2ban -n 20
    exit 1
fi

# Show status
echo ""
echo "========================================="
echo "  Setup Complete!"
echo "========================================="
echo ""
echo "Fail2ban is now protecting your server."
echo ""
echo "Configuration:"
echo "  - Ban time: 1 hour (3600 seconds)"
echo "  - Max retries: 3 attempts"
echo "  - Find time: 10 minutes (600 seconds)"
echo ""
echo "Active jails:"
fail2ban-client status
echo ""
echo "SSH jail status:"
fail2ban-client status sshd
echo ""
echo "Useful commands:"
echo "  sudo fail2ban-client status sshd        # Check SSH jail status"
echo "  sudo fail2ban-client status             # List all jails"
echo "  sudo fail2ban-client set sshd unbanip IP  # Unban an IP"
echo "  sudo tail -f /var/log/fail2ban.log      # Monitor bans"
echo ""
echo "To whitelist your IP, edit /etc/fail2ban/jail.local:"
echo "  ignoreip = 127.0.0.1/8 ::1 YOUR.IP.HERE"
echo ""
